//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Incidencias.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incidencia
    {
        public int id { get; set; }
        public System.DateTime FechaGeneracion { get; set; }
        public int idEstado { get; set; }
        public int idCliente { get; set; }
        public string Descripccion { get; set; }
        public int idResponsable { get; set; }
        public string Solucion { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Responsable Responsable { get; set; }
    }
}
